### ISSUE TITLE
[FIX] onInit 메소드 제거

### ISSUE THREAD

**Issue by DongChyeon** [AdultOfNineteen/WINEY-Android#12]
## 이슈
* 최초 로그인 시 화면에 필요한 정보를 불러오지 못함
* 정보의 실시간 동기화가 되지 않음

## 작업 사항
- [ ] onInit 메소드 제거
- [ ] 각 탭 클릭 시 필요한 정보가 새로고침되도록 로직 수정

**Comment by swa07016** [comment]
열일하는 모습 멋지십니다..
